# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: (classic) Logic App Infrastructure as Code Pipeline. 

on:
  workflow_dispatch:
  push:
    paths:
      - "ARM/**"
      - ".github/workflows/Infra.yml"

jobs:
  DeployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: 
      name: Dev
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
        enable-AzPSSession: true 
    
    - name: Update Logic App Connections 
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show         
          #az functionapp config appsettings set --name ${{ steps.ladeploy.outputs.LAname }} --resource-group  ${{ secrets.RG_LA }} --settings "BLOB_CONNECTION_RUNTIMEURL=${{ steps.msdemoconn.outputs.blobendpointurl }}"
          #az functionapp config appsettings set --name ${{ steps.ladeploy.outputs.LAname }} --resource-group  ${{ secrets.RG_LA }} --settings "WORKFLOWS_RESOURCE_GROUP_NAME=${{ secrets.RG_LA }}"
